import React from 'react'
import styles from "./homePage.module.css"

const HomePage = () => {
  return (
    <main className='mainContent '>
   <p className=' '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro explicabo culpa amet, mollitia obcaecati esse quisquam vero aperiam illum, repudiandae veritatis enim tempore possimus voluptatibus illo quas sequi doloribus at, nemo accusantium nisi et nesciunt molestias ex? Libero optio ex exercitationem accusamus, neque id quod delectus nihil vero, nisi excepturi aperiam ea, unde dolore! Magni, pariatur? Fuga veniam aliquam error voluptate odit deleniti iusto accusamus. Soluta veritatis harum voluptatem sequi accusantium quam ducimus? Vero debitis sit rem quidem sed a, accusamus aliquid repellat, optio dolorum maiores? Impedit, eveniet? Amet illo eos quibusdam deserunt rerum ipsa nostrum officiis unde, quia nobis, doloribus rem? Quaerat deserunt nostrum necessitatibus odit eligendi distinctio assumenda sint labore vitae tempora. Atque error, vero repellendus facilis laudantium voluptatum eveniet inventore temporibus itaque reprehenderit. Nihil facilis vel eum, iure magni odio modi voluptas. Ipsam quis dolorum eaque quidem blanditiis, eum nisi quod quo, ullam assumenda porro nesciunt soluta earum nam dolores eius quaerat tempora alias! Odio voluptas minus qui officia tempora ex recusandae laudantium dignissimos dolore a, laborum natus molestiae veniam pariatur rem maiores quo maxime vero minima soluta doloribus, hic veritatis at. Vel numquam tempore sint optio architecto ex neque dignissimos id, ducimus earum. Corrupti, consequatur, ratione iusto repellendus voluptate commodi nulla doloremque, iure error mollitia quam ex architecto deleniti dolor ducimus sunt sequi facere. Mollitia, aspernatur? Vel ea in voluptates porro, amet quo accusamus! Reiciendis corrupti reprehenderit excepturi laudantium molestiae, aut ea cupiditate eaque voluptatem animi dicta odit quasi id corporis tempore deleniti provident praesentium incidunt illum ullam error ratione ut laborum? Quos voluptates laboriosam deleniti omnis nam similique magnam repudiandae dolores eveniet distinctio, praesentium exercitationem eaque ratione laudantium fugiat fugit optio rem voluptatem ullam odit perferendis temporibus neque eligendi possimus. Ducimus ab tenetur omnis eius. Eaque, asperiores adipisci. Dolore ullam voluptates enim perspiciatis iusto blanditiis.</p>
    </main>
  )
}

export default HomePage
